### ISSUE TITLE
Ros Support for Deepdrive 

### ISSUE THREAD

**Issue by akhil22** [deepdrive/deepdrive#11]
Hi, 
I was looking for ROS support for Deepdrive. I understand that the code base is in python and I can use python to write sensor drivers that can publish the messages over ROS but I was wondering whether its a good idea to write camera drivers and Lidar drivers in Python? If its not a good idea then I would like to write some basic sensor drivers in C++ for Deepdrive.

**Comment by crizCraig** [comment]
Hi Akhil. Three ways i can see to do this: 
1. Write them in C++, within our Unreal plugin using our existing source / sink abstraction. That way, if you use your agent in another environment, or a real car that uses ROS, you can simply send the messages there instead of to our sim. Also, for projects that use our plugin in a different simulation, they would get the ability to use ROS.

2. You can also do it in our gym env in Python, which will be easier but slower. The advantage to this would be that the baseline agent and other derivitive agents would work with ROS.

3. The best of both worlds would be to do it in the Python extension (you could use C++ and Python there).

**Comment by akhil22** [comment]
Hi crizCrag,
I think I would go with the third approach as I would like to test these algorithms on a Truck we have which uses ROS extensively and It has couple of Lidars which would be slower to simulate in python. Thanks for you detailed response.

**Comment by crizCraig** [comment]
Awesome. Let me know if you have any more questions.
